# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Set the number of commands to remember in the command history
HISTSIZE=10000
# Set the number of lines to save in the history file
HISTFILESIZE=10000
# Ignore commands that start with a space
HISTCONTROL=ignorespace

alias gitroot='cd $(git rev-parse --show-toplevel)'
alias cdgit='cd ~/Projects/personal'
alias adios='shutdown -P now'

# Load inputrc settings
if [ -f ~/.inputrc ]; then
    bind -f ~/.inputrc
fi

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# OSC7 escape sequence to open new foot terminal in same directory
osc7_cwd() {
    local strlen=${#PWD}
    local encoded=""
    local pos c o
    for (( pos=0; pos<strlen; pos++ )); do
        c=${PWD:$pos:1}
        case "$c" in
            [-/:_.!\'\(\)~[:alnum:]] ) o="${c}" ;;
            * ) printf -v o '%%%02X' "'${c}" ;;
        esac
        encoded+="${o}"
    done
    printf '\e]7;file://%s%s\e\\' "${HOSTNAME}" "${encoded}"
}
PROMPT_COMMAND=${PROMPT_COMMAND:+${PROMPT_COMMAND%;}; }osc7_cwd
